### ISSUE TITLE
Adding the position of a Day e.g (st, nd, rd, th)

### ISSUE THREAD

**Issue by thayeylolu** [mccutchen/strftime.org#29]
Hello. 
I would like to ask if the strftime module has a function that returns a date with its position . For example ;
02/12/2021  -  2nd
strftime.function_name('02/12/2021')  # returns 2nd 
and
04/11/2021 - 4th 
strftime.function_name('04/12/2021')  # returns 4th

**Comment by mccutchen** [comment]
Hi!  I'm not sure what the "position" of a date is, but the python `strtime` module is documented here:
https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Comment by thayeylolu** [comment]
Hello @mccutchen . Thank you for sharing the link, but it does not contain what I am looking for.  I meant to ask if strftime allows formatting a date with a suffix. Formatting examples like: May 5th, Jan 1st .
 I know it allows formatting like May 5, and Jan 1
